Algoritmo "OPERADORES RELACIONAIS"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 19/01/2023
Var
   A,B,C: Inteiro
// Seção de Declarações das variáveis 


Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
   A<-2
   B<-3
   C<-5
   Escreva(1=C%2)

Fimalgoritmo